esphome:
  name: iot-test-bareesp32
  comment: "ESP32-DEVKIT-V1 (ESP32-WROOM-32)"
  area: "Unknown"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  base: !include packages/nodemcuesp32/base.yaml
  actions: !include packages/nodemcuesp32/actions.yaml

# Any customization go here

