esphome:
  name: iot-test-esp32cam
  comment: "ESP32-Camera Module"
  area: "Unknown"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  base: !include packages/esp32-cam/base.yaml
  actions: !include packages/esp32-cam/actions.yaml

# Any customization go here

