esphome:
  name: iot1
  comment: "NodeMCUv2 (ESP-12E) board DIY"
  area: "Water tank at rooftop"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  mqtt: !include packages/mqtt.yaml
  base: !include packages/nodemcuv2/base.yaml
  actions: !include packages/nodemcuv2/actions.yaml
  dht: !include
    file: packages/macros/sensor-dht.yaml
    vars:
      param_dht_id: "ambient_sensor"
      param_dht_model: "AM2302"
      param_dht_gpio: "GPIO13"
      param_dht_update_interval: "60s"
  ultrasonic: !include
    file: packages/macros/sensor-ultrasonic.yaml
    vars:
      param_ultrasonic_id: "ultrasonic_sensor"
      param_ultrasonic_name: "SENSOR - Water Tank Level"
      param_ultrasonic_trigger_pin: "GPIO14"
      param_ultrassonic_echo_pin: "GPIO12"
      param_ultrasonic_update_interval: "60s"

sensor:
  # add some filters to ultrasonic sensor
  - id: !extend ultrasonic_sensor
    filters:
    - calibrate_linear:
      - from: 0.21
        to: 100.0
      - from: 0.75
        to: 0.0
    - median:
        window_size: 5
        send_every: 1
        send_first_at: 1
