esphome:
  name: iot3
  comment: "Sonoff Basic R2"
  area: "Bancada"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  base: !include packages/sonoff-basic/base.yaml
  actions: !include packages/sonoff-basic/actions.yaml

# Any customization go here
