esphome:
  name: iot5
  comment: "Positivo PPW1001"
  area: "Bancada"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  base: !include packages/positivo-ppw1001/base.yaml
  actions: !include packages/positivo-ppw1001/actions.yaml

# Any customization go here
