esphome:
  name: iot6
  comment: "EKAZA EKGC-T206M Smart Plug (Tuya CB2S/BK7231N)"
  area: "Porta do escritorio"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi.yaml
  mqtt: !include packages/mqtt.yaml
  base: !include packages/ekaza-t206m/base.yaml
  actions: !include packages/ekaza-t206m/actions.yaml

# Any customization go here

