esphome:
  name: iot7
  comment: "WEG Wifi Plugue 10A"
  area: "Ventilador vo"

packages:
  common: !include packages/common.yaml
  wifi: !include packages/wifi2.yaml
  base: !include packages/weg-wifiplugue10a/base.yaml
  actions: !include packages/weg-wifiplugue10a/actions-multi.yaml

# Any customization go here

substitutions:
  # timeout for relay auto-off
  timeout_value: 4h
