# Hardware:
# - brand: WEG, model: Smart Plugue 10A, module: Tuya TYWE2S, MCU: ESP-8285, w/ POW
#
# Module info: https://developer.tuya.com/en/docs/iot/wifie2smodule?id=K9605u79tgxug
#
# Features: Two leds (both controllable), one relay, one switch, POW
#
# +------+---------------------+------------------------------------+------------------------------+
# | Name |   Number   | GPIO   | Function                           | Notes                        |
# +------+---------------------+------------------------------------+------------------------------+
# | RST  |     10     |        | reset (not connected)              |                              |
# | ADC  |      8     |  ADC   | analogic input (not connected)     | Free GPIO (ADC, input only)  | 
# | IO13 |      6     | GPIO13 | Relay, non-inverted                |                              |
# | IO4  |      4     | GPIO4  | bl0937 CF                          |                              |
# | IO5  |      2     | GPIO5  | bl0937 CF1                         |                              |
# | 3V3  |      1     |        | power                              |                              |
# | GND  |      3     |        | power                              |                              |
# | RX0  |      5     | GPIO3  | Push Button w/ hw pullup, inverted | no need to use pull-up in sw |
# | TX0  |      7     | GPIO1  | Blue led, inverted                 |                              |
# | IO12 |      9     | GPIO12 | Red led, inverted                  |                              |
# | IO14 |     11     | GPIO14 | bl0937 SEL, inverted               |                              |
# | IO0  | test point | GPIO0  | (not connected)                    | Free GPIO                    |
# | TX1  | test point | GPIO2  | (not connected)                    | Free GPIO                    |
# +------+------------+--------+------------------------------------+------------------------------+
#
# Notes:
# - Pin numbers above are for the module, not the MCU (this module has different
#   order of pins than most of the others, pay attention to the docs)
# - These are the GPIOs that you can actually access outside of the module
#   the chip inside has many more free GPIOs but they are not exposed so
#   you cannot actually use them for anything useful.
# - In this module, UART TX and RX pins are used for led and push button with pull-up,
#   one of the reasons why it's not easy to flash it in place without desoldering and
#   removing the module from the board

esp8266:
  board: esp8285

# This board uses the RX/TX pins for normal I/O so cannot log over uart
logger:
  baud_rate: 0

# Status led is the Blue one
status_led:
  id: led
  pin:
    number: GPIO1 # TX pin
    mode: OUTPUT
    inverted: True # True (it is inverted)

binary_sensor:
  - platform: gpio
    name: "Push Button"
    id: push_button
    pin:
      number: GPIO3 # RX pin
      mode: INPUT
      inverted: True

switch:
  # The relay
  - platform: gpio
    name: "Relay"
    id: relay
    pin:
      number: GPIO13
      mode: OUTPUT
      inverted: False
  # the relay LED is the red one
  - platform: gpio
    id: relay_led
    name: "Relay LED"
    pin:
      number: GPIO12
      mode: OUTPUT
      inverted: True

# More sensors from macros packages
# passing parameters directly to include instead of doing substitutions allow
# you to have multiple instances with different names
packages:
  # The power measurement chip BL0937
  power_sensor: !include
    file: ../macros/power-bl0937.yaml
    vars:
      parm_power_bl0937_id: "power_sensor"
      parm_power_bl0937_sel_gpio: "GPIO14"
      parm_power_bl0937_sel_inverted: "True"
      parm_power_bl0937_cf: "GPIO4"
      parm_power_bl0937_cf1: "GPIO5"
      parm_power_bl0937_change_mode_every: "1"
      parm_power_bl0937_update_interval: "5s"
      parm_power_bl0937_current_resistor: "0.001 ohm"
      parm_power_bl0937_voltage_divider: "2351" # from esphome doc
      parm_power_bl0937_current_correction: "1.0"
      parm_power_bl0937_voltage_correction: "0.983"
