esphome:
  name: somename
  comment: "Sonoff Mini R4 Extreme"
  area: "somewhere"

packages:
  common: !include esphome-configs/packages/common.yaml
  wifi: !include esphome-configs/packages/wifi.yaml
  base: !include esphome-configs/packages/sonoff-minir4/base.yaml
  actions: !include esphome-configs/packages/sonoff-minir4/actions.yaml

# Any customization go here
