esphome:
  name: somename
  comment: "WirelessTag WT32-ETH01 board"
  area: "somewhere"

packages:
  common: !include esphome-configs/packages/common.yaml
  wifi: !include esphome-configs/packages/wifi.yaml
  base: !include esphome-configs/packages/wirelesstag-wt32eth01/base.yaml
  #ethernet: !include esphome-configs/packages/wirelesstag-wt32eth01/ethernet.yaml
  actions: !include esphome-configs/packages/wirelesstag-wt32eth01/actions.yaml

# Any customization go here
