# Hardware:
# - standard NodeMCU V2 (ESP12-E) board, MCU: ESP-8266
#
# Board info: https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/
# refer to the ESP-12E section
#
# This board have all GPIOs exposed in headers on the board, so the documentation
# above should be sufficient to understand it
#
# It does not have any peripheral except a led and a button (two buttons actually
# but the other one is hardware reset).

esp8266:
  board: nodemcuv2

status_led:
  id: led
  pin:
    number: GPIO2
    mode: OUTPUT
    inverted: true

binary_sensor:
  - platform: gpio
    name: "FLASH Push Button"
    id: push_button
    pin:
      number: GPIO0
      mode: INPUT
      inverted: True

#sensor:
#  - platform: adc
#    pin: A0
#    name: "SENSOR - ADC"
#    update_interval: 60s
