esphome:
  name: somename
  comment: "NodeMCUv2 (ESP-12E) board DIY"
  area: "Somewhere"

packages:
  common: !include esphome-configs/packages/common.yaml
  wifi: !include esphome-configs/packages/wifi.yaml
  base: !include esphome-configs/packages/nodemcuv2/base.yaml
  actions: !include esphome-configs/packages/nodemcuv2/actions.yaml

# Any customization go here

