esphome:
  name: somename
  comment: "EKAZA EKGC-T206M Smart Plug (Tuya CB2S/BK7231N)"
  area: "somewhere"

packages:
  common: github://token47/esphome-configs/packages/common.yaml
  wifi: github://token47/esphome-configs/packages/wifi.yaml
  base: github://token47/esphome-configs/packages/ekaza-t206m/base.yaml
  actions: github://token47/esphome-configs/packages/ekaza-t206m/actions.yaml

# Any customization goes here

