esphome:
  name: somename
  comment: "EKAZA EKGC-T206M Smart Plug (Tuya CB2S/BK7231N)"
  area: "somewhere"

packages:
  common: !include ..../common.yaml
  wifi: !include ..../wifi.yaml
  base: !include ..../ekaza-t206m/base.yaml
  actions: !include ..../ekaza-t206m/actions.yaml

# Any customization goes here
