esphome:
  name: somename
  comment: "EKAZA EKGC-T206M Smart Plug (Tuya CB2S/BK7231N)"
  area: "somewhere"

packages:
  common: !include github://token47/esphome-configs/packages/common.yaml
  wifi: !include github://token47/esphome-configs/packages/wifi.yaml
  base: !include github://token47/esphome-configs/packages/ekaza-t206m/base.yaml
  actions: !include github://token47/esphome-configs/packages/ekaza-t206m/actions.yaml

# Any customization goes here

