# Hardware:
# - standard Wemos D1 Mini (ESP12-E) board, MCU: ESP-8266
#
# Board info: https://lastminuteengineers.com/wemos-d1-mini-pinout-reference/
#
# This board have all GPIOs exposed in headers on the board, so the documentation
# above should be sufficient to understand it
#
# It does not have any peripheral except a reset button (not used by any GPIO).

esp8266:
  board: d1_mini

#sensor:
#  - platform: adc
#    pin: A0
#    name: "SENSOR - ADC"
#    update_interval: 60s
